/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Win32RegKeyEnumeration */

#ifndef _Included_Win32RegKeyEnumeration
#define _Included_Win32RegKeyEnumeration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Win32RegKeyEnumeration
 * Method:    hasMoreElements
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Win32RegKeyEnumeration_hasMoreElements
  (JNIEnv *, jobject);

/*
 * Class:     Win32RegKeyEnumeration
 * Method:    nextElement
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Win32RegKeyEnumeration_nextElement
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
