/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Win32RegKey */

#ifndef _Included_Win32RegKey
#define _Included_Win32RegKey
#ifdef __cplusplus
extern "C" {
#endif
#undef Win32RegKey_HKEY_CLASSES_ROOT
#define Win32RegKey_HKEY_CLASSES_ROOT -2147483648L
#undef Win32RegKey_HKEY_CURRENT_USER
#define Win32RegKey_HKEY_CURRENT_USER -2147483647L
#undef Win32RegKey_HKEY_LOCAL_MACHINE
#define Win32RegKey_HKEY_LOCAL_MACHINE -2147483646L
#undef Win32RegKey_HKEY_USERS
#define Win32RegKey_HKEY_USERS -2147483645L
#undef Win32RegKey_HKEY_CURRENT_CONFIG
#define Win32RegKey_HKEY_CURRENT_CONFIG -2147483643L
#undef Win32RegKey_HKEY_DYN_DATA
#define Win32RegKey_HKEY_DYN_DATA -2147483642L
/*
 * Class:     Win32RegKey
 * Method:    getValue
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_Win32RegKey_getValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Win32RegKey
 * Method:    setValue
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_Win32RegKey_setValue
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
