package ru.aztpa.a.oaa.eng.bom.v01;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated source version: 2.1
 */
@WebService(portName = "BOMPort",
            serviceName = "BOM",
            targetNamespace = "http://www.aztpa.ru/a/oaa/eng/bom/v01/",
            // wsdlLocation = "/wsdls/A_OAA_ENG_BOM_v01.wsdl",
            endpointInterface = "ru.aztpa.a.oaa.eng.bom.v01.BOMPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class BOM_BOMPortImpl implements BOMPortType
{
    private BomPortImplDelegate wsDelegate;
    
    public BOM_BOMPortImpl()
    {
        wsDelegate = new BomPortImplDelegate();
    }

    /**
     * @param fgList
     * @return returns ru.aztpa.a.oaa.eng.bom.v01.ActionResult
     */
    @Override
    public ActionResult makeBomForFgList(PlannedFgList fgList)
    {
        return wsDelegate.makeBomForFgList(fgList);
    }
}
