package ru.aztpa.a.oaa.mfg.legacydata.v01;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import java.sql.SQLException;
import java.util.List;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated source version: 2.1
 * <p/>
 */
@WebService(portName = "LegacyDataSOAP", serviceName = "LegacyData",
            targetNamespace = "http://www.aztpa.ru/a/oaa/mfg/legacydata/v01/",
            // wsdlLocation = "/wsdls/A_OAA_MFG_LegacyData_v01.wsdl",
            endpointInterface = "ru.aztpa.a.oaa.mfg.legacydata.v01.LegacyDataPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class LegacyData_LegacyDataSOAPImpl implements LegacyDataPortType
{
    private CallerMediator caller;
    
    public LegacyData_LegacyDataSOAPImpl()
    {
        caller = new CallerMediator();
    }

    /**
     *
     * @param process
     * <p/>
     * @return returns ru.aztpa.a.oaa.mfg.legacydata.v01.ActionResult
     */
    @Override
    public ActionResult updateProcessOperations(List<TechnologyProcess> process)
    {
        try
        {
            return caller.doUpdateProcessOperations(process);
        }
        catch (SQLException sqlEx)
        {
            throw new RuntimeException(sqlEx);
        }
    }
}
