package ru.aztpa.a.oaa.mfg.wipplan.v01;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 */
@WebService(portName = "WipPlanPortSOAP",
            serviceName = "WipPlan",
            targetNamespace = "http://www.aztpa.ru/a/oaa/mfg/wipplan/v01/",
            endpointInterface = "ru.aztpa.a.oaa.mfg.wipplan.v01.WipPlanPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class WipPlan_WipPlanPortSOAPImpl implements WipPlanPortType
{
    private WipPlanDelegate wsDelegate;

    public WipPlan_WipPlanPortSOAPImpl()
    {
        wsDelegate = new WipPlanDelegate();
    }

    /**
     * @param shop
     * @return returns ru.aztpa.a.oaa.mfg.wipplan.v01.ActionResult
     */
    public ActionResult createWipPlan(Shop shop)
    {
        return wsDelegate.createWipPlan(shop);
    }
}
