/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Printf3 */

#ifndef _Included_Printf3
#define _Included_Printf3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Printf3
 * Method:    fprint
 * Signature: (Ljava/io/PrintWriter;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_Printf3_fprint
  (JNIEnv *, jclass, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
